"""rename department

Revision ID: 63715dd6eb0f
Revises: f26db0855ed2
Create Date: 2025-06-18 13:33:04.778758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63715dd6eb0f'
down_revision = 'f26db0855ed2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', new_table_name='department')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', new_table_name='departments')
    # ### end Alembic commands ###
