"""rename adress

Revision ID: 91de1a47be62
Revises: 63715dd6eb0f
Create Date: 2025-06-18 13:46:22.453358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91de1a47be62'
down_revision = '63715dd6eb0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address', new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location', new_column_name='address')
    # ### end Alembic commands ###
